### ISSUE TITLE
shorthands: create a function for transition property

### ISSUE THREAD

**Issue by kme026** [microsoft/griffel#177]
transition: ".3s cubic-bezier(.33,0,0,1) all" can't be used with griffel atm

**Comment by layershifter** [comment]
For reference: https://developer.mozilla.org/en-US/docs/Web/CSS/transition

---

More or less it looks quite simple as it works in the same way as `borderLeft` as expands to four properties:

```css
/* property name | duration */
transition: margin-right 4s;

/* property name | duration | delay */
transition: margin-right 4s 1s;

/* property name | duration | easing function */
transition: margin-right 4s ease-in-out;

/* property name | duration | easing function | delay */
transition: margin-right 4s ease-in-out 1s;
```

The problem comes with ",":

```css
/* Apply to 2 properties */
transition: margin-right 4s, color 1s;
```

![image](https://user-images.githubusercontent.com/14183168/182364552-a9f3eaed-0051-4a94-b4fa-32214a75c737.png)

I don't have a good idea around about the comma support. Opened for ideas...
