### ISSUE TITLE
bug: mergeClasses order of arguments not working as expected when used with Webpack Extraction plugin

### ISSUE THREAD

**Issue by rafaeltavares** [microsoft/griffel#447]
`mergeClasses` documentation states that:
> ...if two classes apply the same style, the latest class wins.

<img width="306" alt="image" src="https://github.com/microsoft/griffel/assets/4458855/9cfee48e-1c51-492e-89c7-6de539912136">

However, this rule is not applied when Webpack CSS extraction plugin is being used.

---

This issue can be reproduced with `@fluentui/react-components`.
Take Fluent UI's `Button` as example:

<img width="145" alt="image" src="https://github.com/microsoft/griffel/assets/4458855/eac768de-2db5-48c7-b3b7-a42317089e1d">

#### Computed styles without CSS extraction plugin
<img width="513" alt="image" src="https://github.com/microsoft/griffel/assets/4458855/ce2e5274-34c4-4518-8850-fa07993315be">

#### Computed styles with CSS extraction plugin
<img width="512" alt="image" src="https://github.com/microsoft/griffel/assets/4458855/3944825d-6a14-4cd2-b095-6c4205f9e369">

---
```javascript
appearance // transparent
```
`rootStyles[appearance]` are overwritten by `rootBaseClassName`, even though it's being declared after `rootBaseClassName`  
https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-button/src/components/Button/useButtonStyles.styles.ts#L529-L531

This issue prevents any variations from Fluent's Button to be rendered correctly.

**Comment by layershifter** [comment]
Rules in `styles-commond_` should be sorted and deduplicated in the same way as in runtime. This looks like a problem with your setup.

Please check that you're using the latest versions of the plugin and you have proper setup (https://griffel.js.org/react/css-extraction/with-webpack), you should have `GriffelCSSExtractionPlugin` in your config.

**Comment by swese44** [comment]
Hi @layershifter. Please take a closer look at the screenshots of FUI9 Button's computed styles, the `mergeClasses` bug @rafaeltavares identified (including multiple classNames with different values for the same style rule) can be seen in the [official Button Storybook examples](https://react.fluentui.dev/?path=/docs/components-button-togglebutton--default) as well as in our product. Note that the bug doesn't manifest in visual errors unless the Webpack Extraction Plugin is enabled, in which case the order of class names in `griffel.css` appears to introduce the specificity issue.

At this point we don't have a clear repro in our own feature code so it's hard to tell how exactly to reproduce this. We suspect this is either a bug in Griffel's `mergeClasses` there's some type of configuration or API misuse in the FUI9 Button code.

**Comment by layershifter** [comment]
> Hi @layershifter. Please take a closer look at the screenshots of FUI9 Button's computed styles, the `mergeClasses` bug @rafaeltavares identified (including multiple classNames with different values for the same style rule) can be seen in the [official Button Storybook examples](https://react.fluentui.dev/?path=/docs/components-button-togglebutton--default) as well as in our product.

There is no problem with that, it's how the combination of [`makeResetStyles()`](https://griffel.js.org/react/api/make-reset-styles/) and [`makeStyles()`](https://griffel.js.org/react/api/make-styles) works 🐱 

<img width="549" alt="image" src="https://github.com/microsoft/griffel/assets/14183168/45f987b7-3b9b-4bf7-b557-63e365baa7c0">


`makeResetStyles()` produces a monolithic class, `makeStyles()` a set of atomic that will be deduplicated in `mergeClasses()` call. Classes from `makeStyles()` will always win over `makeResetStyles()` because of the order of appearance (that's why deduplication between `makeResetStyles()` and `makeStyles()` is not needed):

```html
<style data-make-styles-bucket="r">
 .reset-styles {}
</style>
<style data-make-styles-bucket="d">
 .atomic-a {}
 .atomic-b {}
 .atomic-c {}
</style>
```

Here is, the example: https://codesandbox.io/s/boring-poitras-5rdxnl?file=/src/App.js

<img width="182" alt="image" src="https://github.com/microsoft/griffel/assets/14183168/7bb1f7ce-9dbd-4245-b31a-e8f0272a1ea7">


----

The problem is that in your stylesheet you have following (wrong order):

```css
/* WRONG ORDER & DUPLICATION 🔴 */
 .atomic-a {}
 .atomic-b {}
 .atomic-b {}
 .atomic-c {}
 .reset-styles {}
```

While it should be:

```css
/* CORRECT ORDER 🟢  */
 .reset-styles {}
 .atomic-a {}
 .atomic-b {}
 .atomic-c {}
```

Please check suggestions from https://github.com/microsoft/griffel/issues/447#issuecomment-1745574462.

**Comment by swese44** [comment]
We'll investigate our webpack config, thank you!
