### ISSUE TITLE
Are there plans to support dynamic parameters

### ISSUE THREAD

**Issue by itmanyong** [microsoft/griffel#90]
Creating styles that are more real-time can feel incongruous! It is not known if Griffel has any plans to support dynamic parameters. Similar to:
`
const useClasses= makeStyles((color)=>({fontColor:{color}}))

const classes = useClasses('red')
`

**Comment by heho** [comment]
@layershifter I do not think that this is a solution that is maintainable in the long run. I tested this on a small scale project and it was wonky at best. On one hand, it requires a lot of additional work from the user which can be faulty and can lead to mixing style with logic. On the other hand it is not possible to typecheck which makes early detection of mistakes during development even harder.

If I could choose an API, it would probably look something like this:
```ts
const useClasses = makeStyles((attr1: string) => {
  root: { color: attr1,
})

function App(props) {
  const classes = useClasses(props.color) // same parameter types as the function passed to makeStyles

  return <div className={classes.root} />
}
```
Then the makeStyles function injects some hashes into the parameters and the useClasses function handles provision of the variables via those hashes. This effectively reduces the amount of work needed to be done for an update while still allowing for changing props to influence the style. However, the work for the creation and injection of the hashes could be a bit more involved, since it would be useful to be able to pass deep objects. But since this work can be done on load it might not be as bad.
There is also the possibility to encourage the current API whilst providing an additional API like the one mentioned for the cases where it is needed.

**Comment by heho** [comment]
Looking at the simpler Problem first, does anything speak against injecting in into a style bucket sheet with `sheet.insertRule(":root{--<hash>: <value>}");` then obtaining a reference to that style rule and modifying the `rule.style.cssText` on prop change? Then you would not need to pass any styles around by hand.

It seems to me that the hash could be generated from the encoded style object by injecting placeholder into the variables. However, in corner cases this would create collisions.

**Comment by heho** [comment]
sorry for coming back to you so late. Corona got me.

Now assuming there is a good solution for creating a hash one could create a helper class with each call of useClasses that is passed around with the classes. This helper class then gets all the variables for the instance of useClasses.

```js
function Foo() {
  const classes1 = useClasses({ color: 'red' }) // produces something like { root: ["abc123", "h3lp3r"], helpers: ["h3lp3r"] }
  const classes2 = useClasses({ color: 'blue })  // produces something like { root: ["abc123", "r3pl3h"], helpers: ["r3pl3h"] }

  return (
     <>
       <div className={classes1.root} />
       <div className={classes2.root} />
     </>
  )
}
```

where the previous still holds true that the helper classes get updated when the props object is updated. However this looks like it would make the problem of finding hashes even worse.
