### ISSUE TITLE
Issues with Griffel versioning

### ISSUE THREAD

**Issue by SaahilChawande** [microsoft/griffel#91]
@griffel/react with version 1.0.0 has a dependency on @griffel/core with version 1.0.7
But @griffel/react with version 1.0.3 has a dependency on @griffel/core with version 1.2.0 which caused issues with using mergeClasses().

The console gave the following error:
`mergeClasses(): a passed string contains an identifier (___1pqbv0t) that does not match any entry in cache.`

Please make sure that minor bumps in versioning, do not create this level of breaking change.

I have fixed the issue currently by using `"@griffel/core": "1.0.7"` and `"@griffel/react": "1.0.0"`.

**Comment by layershifter** [comment]
Sorry, but the problem is not clear to me.

---

In your application you need to use `@griffel/react`. Once `@griffel/react` will be bumped - `@griffel/core` will be bumped automatically as it's a sub-dependency:

![image](https://user-images.githubusercontent.com/14183168/163676126-7fa88554-8e87-471d-ba48-658b533a6b52.png)

The problem might that you mentioned might happen when you have multiple versions of `@griffel/core` installed in `node_modules`. You can find out this in `yarn.lock` or `package-lock.json`.

Can you please provide a repro case or more details?
